services:
  lil-mo:
    container_name: lil-mo
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /var/log/lil-mo:/logs
    environment:
      - TOKEN=${TOKEN:-ADD_TOKEN}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID:-ADD_SPOTIFY_CLIENT_ID}
      - SPOTIFY_SECRET=${SPOTIFY_SECRET:-ADD_SPOTIFY_SECRET}